-- =====================================================================
-- Seguros Castaño - Sistema de atención al cliente con Bot IA
-- Esquema PostgreSQL 17 (base "proyecto", schema public)
--
-- Uso:  docker exec -i postgres-irusu psql -U irusu -d proyecto -v ON_ERROR_STOP=1 < 01_schema.sql
-- No usa IF NOT EXISTS a propósito: si ya existe, falla en vez de pisar datos.
-- Para recrear desde cero ver 00_drop_all.sql (destructivo).
--
-- Convenciones
--   * PK: id bigint identity. Códigos de negocio (POL-00123, CASO-001) en columnas UNIQUE.
--   * DNI: solo dígitos (sin puntos). WhatsApp: formato canónico +549 + 10 dígitos.
--   * Estados como text + CHECK (fácil de usar como `choices` en Django).
--   * Django: mapear con managed = False (python manage.py inspectdb).
-- =====================================================================

-- ---------------------------------------------------------------------
-- Equipo de la agencia (quienes usan el panel de supervisión)
-- ---------------------------------------------------------------------
CREATE TABLE funcionarios (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        text    NOT NULL,
    email         text    NOT NULL UNIQUE,
    rol           text    NOT NULL CHECK (rol IN ('propietario', 'administracion', 'operador')),
    puede_aprobar boolean NOT NULL DEFAULT false,  -- puede aprobar/rechazar acciones del bot
    activo        boolean NOT NULL DEFAULT true,
    creado_en     timestamptz NOT NULL DEFAULT now()
);
COMMENT ON COLUMN funcionarios.puede_aprobar IS
    'Solo quien tenga true puede aprobar acciones críticas (baja, modificación, reembolso). Lo fuerza un trigger.';

-- ---------------------------------------------------------------------
-- Catálogos (reemplazan el "Automotor / auto / AUTO" del Excel)
-- ---------------------------------------------------------------------
CREATE TABLE tipos_seguro (
    id     smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo text NOT NULL UNIQUE CHECK (codigo = lower(codigo)),
    nombre text NOT NULL
);

-- politica = qué puede hacer el bot con este tipo de consulta
--   bot_responde         : consulta de rutina, el bot contesta solo (igual queda registrada)
--   requiere_aprobacion  : acción contractual; el bot solo puede registrar la solicitud
--   derivar_humano       : el bot debe derivar y avisar a un funcionario
--   seguridad            : intento de manipulación del bot
CREATE TABLE tipos_consulta (
    id      smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo  text NOT NULL UNIQUE CHECK (codigo = lower(codigo)),
    nombre  text NOT NULL,
    politica text NOT NULL CHECK (politica IN ('bot_responde', 'requiere_aprobacion', 'derivar_humano', 'seguridad'))
);

-- ---------------------------------------------------------------------
-- Clientes, contactos de WhatsApp, pólizas
-- ---------------------------------------------------------------------
CREATE TABLE clientes (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni       text NOT NULL UNIQUE CHECK (dni ~ '^[0-9]{7,8}$'),  -- sin puntos: evita duplicados "28.111.222" vs "28111222"
    nombre    text NOT NULL,
    apellido  text NOT NULL,
    email     text,
    activo    boolean NOT NULL DEFAULT true,
    creado_en timestamptz NOT NULL DEFAULT now()
);

-- Un número de WhatsApp puede pertenecer a un cliente o ser desconocido (prospecto / atacante).
CREATE TABLE contactos_whatsapp (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero     text NOT NULL UNIQUE CHECK (numero ~ '^\+549[0-9]{10}$'),
    cliente_id bigint REFERENCES clientes (id),
    creado_en  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX contactos_whatsapp_cliente_idx ON contactos_whatsapp (cliente_id);

CREATE TABLE polizas (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_poliza     text NOT NULL UNIQUE CHECK (numero_poliza ~ '^POL-[0-9]{5}$'),
    cliente_id        bigint NOT NULL REFERENCES clientes (id),
    tipo_seguro_id    smallint NOT NULL REFERENCES tipos_seguro (id),
    cobertura         text NOT NULL CHECK (cobertura IN ('basica', 'intermedia', 'total')),
    estado            text NOT NULL DEFAULT 'vigente' CHECK (estado IN ('vigente', 'vencida', 'dada_de_baja')),
    fecha_inicio      date NOT NULL,
    fecha_vencimiento date NOT NULL,
    prima_mensual     numeric(12,2) NOT NULL CHECK (prima_mensual >= 0),
    bien_asegurado    text,
    creado_en         timestamptz NOT NULL DEFAULT now(),
    CHECK (fecha_vencimiento > fecha_inicio)
);
CREATE INDEX polizas_cliente_idx ON polizas (cliente_id);

CREATE TABLE conductores_poliza (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poliza_id   bigint NOT NULL REFERENCES polizas (id),
    nombre      text NOT NULL,
    dni         text NOT NULL CHECK (dni ~ '^[0-9]{7,8}$'),
    relacion    text NOT NULL CHECK (relacion IN ('titular', 'conyuge', 'hijo', 'otro')),
    activo      boolean NOT NULL DEFAULT true,
    UNIQUE (poliza_id, dni)
);

-- Cuotas: permite verificar lo que el bot dice sobre saldo y vencimiento de pago
CREATE TABLE cuotas (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poliza_id      bigint NOT NULL REFERENCES polizas (id),
    periodo        date NOT NULL CHECK (extract(day FROM periodo) = 1),  -- primer día del mes
    importe        numeric(12,2) NOT NULL CHECK (importe >= 0),
    vencimiento    date NOT NULL,
    estado         text NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'pagada', 'vencida')),
    fecha_pago     date,
    importe_pagado numeric(12,2) CHECK (importe_pagado >= 0),
    UNIQUE (poliza_id, periodo),
    CHECK ((estado = 'pagada') = (fecha_pago IS NOT NULL AND importe_pagado IS NOT NULL))
);
CREATE INDEX cuotas_poliza_estado_idx ON cuotas (poliza_id, estado);

-- ---------------------------------------------------------------------
-- Consultas atendidas por el bot (todo lo que dice el bot queda guardado)
-- ---------------------------------------------------------------------
CREATE TABLE consultas_bot (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_caso             text NOT NULL UNIQUE CHECK (codigo_caso ~ '^CASO-[0-9]{3,}$'),
    fecha_hora              timestamptz NOT NULL,
    contacto_id             bigint REFERENCES contactos_whatsapp (id),   -- NULL si el mensaje llegó sin número
    mensaje_usuario         text NOT NULL,
    respuesta_bot           text NOT NULL,
    tipo_consulta_id        smallint NOT NULL REFERENCES tipos_consulta (id),
    estado                  text NOT NULL DEFAULT 'pendiente_revision'
                            CHECK (estado IN ('abierto', 'pendiente_revision', 'derivado', 'cerrado')),
    funcionario_asignado_id bigint REFERENCES funcionarios (id),
    fecha_resolucion        date,
    -- Revisión humana (human-in-the-loop)
    revisado_por_id         bigint REFERENCES funcionarios (id),
    revisado_en             timestamptz,
    respuesta_corregida     text,          -- lo que Graciela le dice finalmente al cliente
    nota_revision           text,
    -- Trazabilidad de la importación del Excel/CSV
    notas_importacion       text,
    datos_origen            jsonb,         -- fila original sin limpiar
    creado_en               timestamptz NOT NULL DEFAULT now(),
    CHECK (fecha_resolucion IS NULL
           OR fecha_resolucion >= (fecha_hora AT TIME ZONE 'America/Argentina/Buenos_Aires')::date),
    CHECK ((revisado_por_id IS NULL) = (revisado_en IS NULL))
);
CREATE INDEX consultas_bot_fecha_idx    ON consultas_bot (fecha_hora DESC);
CREATE INDEX consultas_bot_estado_idx   ON consultas_bot (estado);
CREATE INDEX consultas_bot_contacto_idx ON consultas_bot (contacto_id);

-- Alertas del panel de supervisión (una consulta puede tener varias)
CREATE TABLE alertas (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consulta_id    bigint NOT NULL REFERENCES consultas_bot (id) ON DELETE CASCADE,
    tipo           text NOT NULL CHECK (tipo IN (
                       'prompt_injection',      -- intento de manipular al bot
                       'fuga_datos',            -- el bot expuso datos de clientes
                       'accion_sin_aprobacion', -- el bot dijo haber ejecutado una acción crítica
                       'dato_inventado',        -- referencia a algo que no existe (siniestro, póliza, link)
                       'dato_inconsistente',    -- contradice los datos reales (fechas, montos, estado)
                       'dato_no_verificado'     -- afirmación sin respaldo (precios, cláusulas)
                   )),
    severidad      text NOT NULL CHECK (severidad IN ('baja', 'media', 'alta', 'critica')),
    descripcion    text NOT NULL,
    origen         text NOT NULL DEFAULT 'automatica' CHECK (origen IN ('automatica', 'manual')),
    estado         text NOT NULL DEFAULT 'abierta' CHECK (estado IN ('abierta', 'en_revision', 'resuelta', 'descartada')),
    creada_en      timestamptz NOT NULL DEFAULT now(),
    resuelta_por_id bigint REFERENCES funcionarios (id),
    resuelta_en    timestamptz,
    resolucion     text,
    CHECK ((estado IN ('resuelta', 'descartada')) = (resuelta_por_id IS NOT NULL AND resuelta_en IS NOT NULL))
);
CREATE INDEX alertas_consulta_idx ON alertas (consulta_id);
CREATE INDEX alertas_abiertas_idx ON alertas (severidad) WHERE estado IN ('abierta', 'en_revision');

-- Derivaciones a un humano ("que el bot derive y nos avise")
CREATE TABLE derivaciones (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consulta_id    bigint NOT NULL REFERENCES consultas_bot (id) ON DELETE CASCADE,
    derivado_a_id  bigint NOT NULL REFERENCES funcionarios (id),
    prioridad      text NOT NULL DEFAULT 'normal' CHECK (prioridad IN ('normal', 'urgente')),
    motivo         text NOT NULL,
    creada_en      timestamptz NOT NULL DEFAULT now(),
    atendida_en    timestamptz
);
CREATE INDEX derivaciones_pendientes_idx ON derivaciones (derivado_a_id) WHERE atendida_en IS NULL;

-- Siniestros (para poder verificar números de siniestro que cita el bot)
CREATE TABLE siniestros (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_siniestro text NOT NULL UNIQUE CHECK (numero_siniestro ~ '^SIN-[0-9]{4}-[0-9]{5}$'),
    poliza_id        bigint NOT NULL REFERENCES polizas (id),
    consulta_id      bigint REFERENCES consultas_bot (id),   -- consulta que originó la denuncia, si hubo
    fecha_ocurrencia date NOT NULL,
    descripcion      text NOT NULL,
    estado           text NOT NULL DEFAULT 'denunciado'
                     CHECK (estado IN ('denunciado', 'en_evaluacion', 'aprobado', 'rechazado', 'cerrado')),
    creado_en        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX siniestros_poliza_idx ON siniestros (poliza_id);

-- ---------------------------------------------------------------------
-- Cola de acciones críticas: el bot solo SOLICITA, un humano aprueba
-- ---------------------------------------------------------------------
CREATE TABLE acciones_pendientes (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consulta_id    bigint NOT NULL REFERENCES consultas_bot (id),
    poliza_id      bigint REFERENCES polizas (id),
    tipo_accion    text NOT NULL CHECK (tipo_accion IN
                       ('baja_poliza', 'agregar_conductor', 'modificar_poliza', 'reembolso', 'apertura_siniestro')),
    parametros     jsonb NOT NULL DEFAULT '{}'::jsonb,
    estado         text NOT NULL DEFAULT 'pendiente'
                   CHECK (estado IN ('pendiente', 'aprobada', 'rechazada', 'ejecutada')),
    solicitada_en  timestamptz NOT NULL DEFAULT now(),
    resuelta_por_id bigint REFERENCES funcionarios (id),
    resuelta_en    timestamptz,
    motivo         text,
    CHECK ((estado = 'pendiente') = (resuelta_por_id IS NULL AND resuelta_en IS NULL))
);
CREATE INDEX acciones_pendientes_estado_idx ON acciones_pendientes (estado);

-- Garantía a nivel base de datos: solo quien tiene puede_aprobar resuelve una acción,
-- y una acción solo puede pasar a 'ejecutada' si antes estuvo 'aprobada'.
CREATE FUNCTION acciones_pendientes_control() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.estado <> 'pendiente' THEN
        IF NOT EXISTS (SELECT 1 FROM funcionarios WHERE id = NEW.resuelta_por_id AND puede_aprobar AND activo) THEN
            RAISE EXCEPTION 'La acción % solo puede ser resuelta por un funcionario activo con permiso de aprobación', NEW.id
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;
    IF TG_OP = 'INSERT' AND NEW.estado <> 'pendiente' THEN
        RAISE EXCEPTION 'Una acción nueva debe crearse en estado pendiente' USING ERRCODE = 'check_violation';
    END IF;
    IF TG_OP = 'UPDATE' THEN
        IF OLD.estado IN ('rechazada', 'ejecutada') AND NEW.estado <> OLD.estado THEN
            RAISE EXCEPTION 'La acción % ya está %, no se puede modificar', OLD.id, OLD.estado
                USING ERRCODE = 'check_violation';
        END IF;
        IF NEW.estado = 'ejecutada' AND OLD.estado <> 'aprobada' THEN
            RAISE EXCEPTION 'La acción % no puede ejecutarse sin aprobación previa', OLD.id
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;
    RETURN NEW;
END $$;

CREATE TRIGGER acciones_pendientes_control_trg
    BEFORE INSERT OR UPDATE ON acciones_pendientes
    FOR EACH ROW EXECUTE FUNCTION acciones_pendientes_control();

-- ---------------------------------------------------------------------
-- Vistas para el panel
-- ---------------------------------------------------------------------

-- Una fila por consulta, con color de alerta (rojo / naranja / amarillo / verde)
CREATE VIEW v_consultas_supervision AS
SELECT c.id,
       c.codigo_caso,
       c.fecha_hora,
       cw.numero              AS whatsapp,
       cl.apellido || ', ' || cl.nombre AS cliente,
       tc.codigo              AS tipo_consulta,
       tc.politica,
       c.mensaje_usuario,
       c.respuesta_bot,
       c.estado,
       f.nombre               AS funcionario_asignado,
       COALESCE(a.alertas_abiertas, 0) AS alertas_abiertas,
       a.severidad_maxima,
       CASE a.severidad_maxima
            WHEN 'critica' THEN 'rojo'
            WHEN 'alta'    THEN 'naranja'
            WHEN 'media'   THEN 'amarillo'
            WHEN 'baja'    THEN 'amarillo'
            ELSE 'verde'
       END                    AS color,
       (c.estado = 'cerrado' AND COALESCE(a.alertas_abiertas, 0) > 0) AS cerrado_con_alerta,
       c.revisado_en IS NOT NULL AS revisada
FROM consultas_bot c
JOIN tipos_consulta tc           ON tc.id = c.tipo_consulta_id
LEFT JOIN contactos_whatsapp cw  ON cw.id = c.contacto_id
LEFT JOIN clientes cl            ON cl.id = cw.cliente_id
LEFT JOIN funcionarios f         ON f.id = c.funcionario_asignado_id
LEFT JOIN LATERAL (
    SELECT count(*) AS alertas_abiertas,
           (ARRAY['baja','media','alta','critica'])[max(CASE al.severidad
                WHEN 'baja' THEN 1 WHEN 'media' THEN 2 WHEN 'alta' THEN 3 ELSE 4 END)] AS severidad_maxima
    FROM alertas al
    WHERE al.consulta_id = c.id AND al.estado IN ('abierta', 'en_revision')
) a ON true;

-- Datos reales de cada póliza, para contrastar contra lo que dijo el bot
CREATE VIEW v_polizas_resumen AS
SELECT p.id AS poliza_id,
       p.numero_poliza,
       cl.apellido || ', ' || cl.nombre AS cliente,
       cl.dni,
       ts.nombre AS tipo_seguro,
       p.cobertura,
       p.estado,
       p.fecha_vencimiento,
       COALESCE(sum(q.importe) FILTER (WHERE q.estado IN ('pendiente', 'vencida')), 0) AS saldo_pendiente,
       min(q.vencimiento) FILTER (WHERE q.estado IN ('pendiente', 'vencida'))          AS proximo_vencimiento_pago
FROM polizas p
JOIN clientes cl     ON cl.id = p.cliente_id
JOIN tipos_seguro ts ON ts.id = p.tipo_seguro_id
LEFT JOIN cuotas q   ON q.poliza_id = p.id
GROUP BY p.id, cl.id, ts.id;
