-- =====================================================================
-- Canal WhatsApp: conversaciones y mensajes
-- Uso (después de 01 y 02):
--   docker exec -i postgres-irusu psql -U irusu -d proyecto -v ON_ERROR_STOP=1 < 03_whatsapp.sql
--
-- Modelo:
--   contactos_whatsapp 1--N conversaciones 1--N mensajes
--   consultas_bot = "caso" (intención detectada) dentro de una conversación; agrupa mensajes.
--   alertas.mensaje_id apunta a la respuesta del bot que disparó la alerta.
--
-- Flujo esperado del backend (webhook de WhatsApp Cloud API):
--   1. Llega mensaje -> INSERT mensajes (entrante, estado_envio='recibido', wa_message_id UNIQUE evita duplicados
--      cuando Meta reintenta el webhook).
--   2. El bot genera respuesta -> INSERT mensajes (saliente, emisor='bot'):
--        'pendiente_envio' si pasa los controles, 'retenido' si dispara una alerta
--        (el cliente NO la recibe hasta que Graciela/Roberto la aprueben o la corrijan).
--   3. Callbacks de estado de Meta actualizan estado_envio: enviado -> entregado -> leido / fallido.
--   4. Si la conversación pasa a modo='humano', el bot deja de responder y escribe el funcionario.
-- Tokens y secretos de la API de WhatsApp NO van en la base: van en variables de entorno.
-- =====================================================================
BEGIN;

ALTER TABLE contactos_whatsapp ADD COLUMN nombre_perfil text;  -- nombre que muestra WhatsApp

-- ---------------------------------------------------------------------
CREATE TABLE conversaciones (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contacto_id               bigint NOT NULL REFERENCES contactos_whatsapp (id),
    estado                    text NOT NULL DEFAULT 'abierta' CHECK (estado IN ('abierta', 'cerrada')),
    modo                      text NOT NULL DEFAULT 'bot' CHECK (modo IN ('bot', 'humano')),  -- quién atiende
    funcionario_id            bigint REFERENCES funcionarios (id),   -- quien tomó la conversación
    ultimo_mensaje_cliente_en timestamptz,   -- WhatsApp solo permite texto libre dentro de las 24 h de este instante
    creada_en                 timestamptz NOT NULL DEFAULT now(),
    cerrada_en                timestamptz,
    CHECK ((estado = 'cerrada') = (cerrada_en IS NOT NULL)),
    CHECK (modo = 'bot' OR funcionario_id IS NOT NULL)
);
-- Un contacto tiene a lo sumo una conversación abierta
CREATE UNIQUE INDEX conversaciones_una_abierta_idx ON conversaciones (contacto_id) WHERE estado = 'abierta';

CREATE TABLE mensajes (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversacion_id bigint NOT NULL REFERENCES conversaciones (id) ON DELETE CASCADE,
    consulta_id     bigint REFERENCES consultas_bot (id),
    direccion       text NOT NULL CHECK (direccion IN ('entrante', 'saliente')),
    emisor          text NOT NULL CHECK (emisor IN ('cliente', 'bot', 'funcionario')),
    funcionario_id  bigint REFERENCES funcionarios (id),     -- solo si emisor = 'funcionario'
    texto           text NOT NULL,
    estado_envio    text NOT NULL CHECK (estado_envio IN
                        ('recibido', 'pendiente_envio', 'retenido', 'enviado', 'entregado', 'leido', 'fallido')),
    wa_message_id   text UNIQUE,      -- id de WhatsApp (wamid...): idempotencia ante reintentos del webhook
    error           text,
    payload         jsonb,            -- JSON crudo del webhook, para depurar
    fecha_hora      timestamptz NOT NULL DEFAULT now(),
    enviado_en      timestamptz,
    CHECK ((emisor = 'cliente') = (direccion = 'entrante')),
    CHECK ((emisor = 'funcionario') = (funcionario_id IS NOT NULL)),
    CHECK ((direccion = 'entrante') = (estado_envio = 'recibido'))
);
CREATE INDEX mensajes_conversacion_idx ON mensajes (conversacion_id, fecha_hora);
CREATE INDEX mensajes_consulta_idx     ON mensajes (consulta_id);
CREATE INDEX mensajes_retenidos_idx    ON mensajes (fecha_hora) WHERE estado_envio IN ('retenido', 'pendiente_envio');
COMMENT ON COLUMN mensajes.estado_envio IS
    'retenido = respuesta del bot frenada por el panel de supervisión; no se envía hasta que un humano la libere.';

ALTER TABLE consultas_bot ADD COLUMN conversacion_id bigint REFERENCES conversaciones (id);
CREATE INDEX consultas_bot_conversacion_idx ON consultas_bot (conversacion_id);
ALTER TABLE alertas ADD COLUMN mensaje_id bigint REFERENCES mensajes (id);   -- respuesta del bot que la originó
CREATE INDEX alertas_mensaje_idx ON alertas (mensaje_id);

-- El texto ahora vive en `mensajes`; estas columnas quedan como resumen opcional del caso (legado del CSV)
ALTER TABLE consultas_bot ALTER COLUMN mensaje_usuario DROP NOT NULL;
ALTER TABLE consultas_bot ALTER COLUMN respuesta_bot   DROP NOT NULL;

-- ---------------------------------------------------------------------
-- Migrar los casos ya cargados (una conversación por contacto)
-- ---------------------------------------------------------------------
INSERT INTO conversaciones (contacto_id, estado, modo, funcionario_id, ultimo_mensaje_cliente_en, creada_en, cerrada_en)
SELECT c.contacto_id,
       CASE WHEN bool_and(c.estado = 'cerrado') THEN 'cerrada' ELSE 'abierta' END,
       CASE WHEN bool_or(d.id IS NOT NULL) THEN 'humano' ELSE 'bot' END,    -- derivación pendiente = lo atiende un humano
       max(d.derivado_a_id),
       max(c.fecha_hora),
       min(c.fecha_hora),
       CASE WHEN bool_and(c.estado = 'cerrado') THEN max(c.fecha_hora) END
FROM consultas_bot c
LEFT JOIN derivaciones d ON d.consulta_id = c.id AND d.atendida_en IS NULL
WHERE c.contacto_id IS NOT NULL
GROUP BY c.contacto_id;

UPDATE consultas_bot SET conversacion_id = (SELECT id FROM conversaciones v WHERE v.contacto_id = consultas_bot.contacto_id)
WHERE contacto_id IS NOT NULL;

-- Mensaje del cliente
INSERT INTO mensajes (conversacion_id, consulta_id, direccion, emisor, texto, estado_envio, fecha_hora)
SELECT conversacion_id, id, 'entrante', 'cliente', mensaje_usuario, 'recibido', fecha_hora
FROM consultas_bot WHERE conversacion_id IS NOT NULL;

-- Respuesta del bot (histórico: ya fue enviada; la hora exacta no se conoce, se usa +5 s)
INSERT INTO mensajes (conversacion_id, consulta_id, direccion, emisor, texto, estado_envio, fecha_hora, enviado_en)
SELECT conversacion_id, id, 'saliente', 'bot', respuesta_bot, 'enviado',
       fecha_hora + interval '5 seconds', fecha_hora + interval '5 seconds'
FROM consultas_bot WHERE conversacion_id IS NOT NULL;

UPDATE alertas a SET mensaje_id = (SELECT m.id FROM mensajes m
                                   WHERE m.consulta_id = a.consulta_id AND m.emisor = 'bot' ORDER BY m.id LIMIT 1);

UPDATE consultas_bot SET notas_importacion = concat_ws(' ', notas_importacion,
    'Sin número de WhatsApp: no se creó conversación ni mensajes.')
WHERE conversacion_id IS NULL;

-- ---------------------------------------------------------------------
-- Bandeja del dashboard: una fila por conversación
-- ---------------------------------------------------------------------
CREATE VIEW v_bandeja_conversaciones AS
SELECT cv.id AS conversacion_id,
       cw.numero AS whatsapp,
       cl.apellido || ', ' || cl.nombre AS cliente,
       cv.estado,
       cv.modo,
       f.nombre AS atendida_por,
       um.texto AS ultimo_mensaje,
       um.emisor AS ultimo_emisor,
       um.fecha_hora AS ultimo_mensaje_en,
       COALESCE(al.alertas_abiertas, 0) AS alertas_abiertas,
       COALESCE(rt.retenidos, 0)        AS respuestas_retenidas,
       (now() - cv.ultimo_mensaje_cliente_en) < interval '24 hours' AS ventana_24h_abierta
FROM conversaciones cv
JOIN contactos_whatsapp cw ON cw.id = cv.contacto_id
LEFT JOIN clientes cl      ON cl.id = cw.cliente_id
LEFT JOIN funcionarios f   ON f.id = cv.funcionario_id
LEFT JOIN LATERAL (
    SELECT m.texto, m.emisor, m.fecha_hora FROM mensajes m
    WHERE m.conversacion_id = cv.id ORDER BY m.fecha_hora DESC, m.id DESC LIMIT 1
) um ON true
LEFT JOIN LATERAL (
    SELECT count(*) AS alertas_abiertas FROM alertas a
    JOIN consultas_bot c ON c.id = a.consulta_id
    WHERE c.conversacion_id = cv.id AND a.estado IN ('abierta', 'en_revision')
) al ON true
LEFT JOIN LATERAL (
    SELECT count(*) AS retenidos FROM mensajes m
    WHERE m.conversacion_id = cv.id AND m.estado_envio = 'retenido'
) rt ON true;

COMMIT;
