from __future__ import annotations

from django.urls import path

from api.paginas import servir_pagina
from api.views import (
    accion_aprobar,
    accion_detalle,
    accion_parametros,
    accion_rechazar,
    acciones_listar,
    alertas_listar,
    auth_csrf,
    auth_login,
    auth_logout,
    auth_me,
    cliente_baja,
    cliente_detalle_o_modificar,
    cliente_reactivar,
    clientes_listar_o_crear,
    consultas_cerradas_con_alertas,
    consulta_reabrir,
    conversacion_devolver,
    conversacion_detalle,
    conversacion_responder,
    conversacion_tomar,
    conversaciones_listar,
    derivacion_atender,
    derivaciones_listar,
    mensaje_descartar,
    mensaje_liberar,
    mensajes_conversacion,
    pendientes,
    poliza_detalle,
)
from api.webhook import webhook_whatsapp

urlpatterns = [
    path("api/auth/csrf/", auth_csrf, name="api_auth_csrf"),
    path("api/auth/login/", auth_login, name="api_auth_login"),
    path("api/auth/logout/", auth_logout, name="api_auth_logout"),
    path("api/auth/me/", auth_me, name="api_auth_me"),
    path("api/pendientes/", pendientes, name="api_pendientes"),
    path("api/conversaciones/", conversaciones_listar, name="api_conversaciones"),
    path("api/conversaciones/<int:id>/", conversacion_detalle, name="api_conversacion_detalle"),
    path("api/conversaciones/<int:id>/mensajes/", mensajes_conversacion, name="api_conversacion_mensajes"),
    path("api/conversaciones/<int:id>/tomar/", conversacion_tomar, name="api_conversacion_tomar"),
    path("api/conversaciones/<int:id>/devolver/", conversacion_devolver, name="api_conversacion_devolver"),
    path("api/conversaciones/<int:id>/responder/", conversacion_responder, name="api_conversacion_responder"),
    path("api/mensajes/<int:id>/liberar/", mensaje_liberar, name="api_mensaje_liberar"),
    path("api/mensajes/<int:id>/descartar/", mensaje_descartar, name="api_mensaje_descartar"),
    path("api/alertas/", alertas_listar, name="api_alertas"),
    path("api/consultas/cerradas-con-alertas/", consultas_cerradas_con_alertas, name="api_consultas_cerradas"),
    path("api/consultas/<int:id>/reabrir/", consulta_reabrir, name="api_consulta_reabrir"),
    path("api/acciones/", acciones_listar, name="api_acciones"),
    path("api/acciones/<int:id>/", accion_detalle, name="api_accion_detalle"),
    path("api/acciones/<int:id>/parametros/", accion_parametros, name="api_accion_parametros"),
    path("api/acciones/<int:id>/aprobar/", accion_aprobar, name="api_accion_aprobar"),
    path("api/acciones/<int:id>/rechazar/", accion_rechazar, name="api_accion_rechazar"),
    path("api/derivaciones/", derivaciones_listar, name="api_derivaciones"),
    path("api/derivaciones/<int:id>/atender/", derivacion_atender, name="api_derivacion_atender"),
    path("api/clientes/", clientes_listar_o_crear, name="api_clientes"),
    path("api/clientes/<int:id>/", cliente_detalle_o_modificar, name="api_cliente_detalle"),
    path("api/clientes/<int:id>/baja/", cliente_baja, name="api_cliente_baja"),
    path("api/clientes/<int:id>/reactivar/", cliente_reactivar, name="api_cliente_reactivar"),
    path("api/polizas/<int:id>/", poliza_detalle, name="api_poliza_detalle"),
    path("webhook/whatsapp/", webhook_whatsapp, name="webhook_whatsapp"),
    path("", servir_pagina, name="pagina_index"),
    path("panel/", servir_pagina, name="pagina_panel"),
    path("panel/conversacion/", servir_pagina, name="pagina_conversacion"),
    path("panel/alertas/", servir_pagina, name="pagina_alertas"),
    path("panel/cerrados/", servir_pagina, name="pagina_cerrados"),
    path("panel/acciones/", servir_pagina, name="pagina_acciones"),
    path("panel/derivaciones/", servir_pagina, name="pagina_derivaciones"),
    path("panel/clientes/", servir_pagina, name="pagina_clientes"),
    path("panel/cliente/", servir_pagina, name="pagina_cliente"),
]
